/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PetaRouteImport } from './routes/peta'
import { Route as PerbandinganRouteImport } from './routes/perbandingan'
import { Route as DataKostRouteImport } from './routes/data-kost'
import { Route as AnalisisRouteImport } from './routes/analisis'
import { Route as IndexRouteImport } from './routes/index'
import { Route as KostKostIdRouteImport } from './routes/kost.$kostId'

const PetaRoute = PetaRouteImport.update({
  id: '/peta',
  path: '/peta',
  getParentRoute: () => rootRouteImport,
} as any)
const PerbandinganRoute = PerbandinganRouteImport.update({
  id: '/perbandingan',
  path: '/perbandingan',
  getParentRoute: () => rootRouteImport,
} as any)
const DataKostRoute = DataKostRouteImport.update({
  id: '/data-kost',
  path: '/data-kost',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalisisRoute = AnalisisRouteImport.update({
  id: '/analisis',
  path: '/analisis',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const KostKostIdRoute = KostKostIdRouteImport.update({
  id: '/kost/$kostId',
  path: '/kost/$kostId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analisis': typeof AnalisisRoute
  '/data-kost': typeof DataKostRoute
  '/perbandingan': typeof PerbandinganRoute
  '/peta': typeof PetaRoute
  '/kost/$kostId': typeof KostKostIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analisis': typeof AnalisisRoute
  '/data-kost': typeof DataKostRoute
  '/perbandingan': typeof PerbandinganRoute
  '/peta': typeof PetaRoute
  '/kost/$kostId': typeof KostKostIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analisis': typeof AnalisisRoute
  '/data-kost': typeof DataKostRoute
  '/perbandingan': typeof PerbandinganRoute
  '/peta': typeof PetaRoute
  '/kost/$kostId': typeof KostKostIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analisis'
    | '/data-kost'
    | '/perbandingan'
    | '/peta'
    | '/kost/$kostId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analisis'
    | '/data-kost'
    | '/perbandingan'
    | '/peta'
    | '/kost/$kostId'
  id:
    | '__root__'
    | '/'
    | '/analisis'
    | '/data-kost'
    | '/perbandingan'
    | '/peta'
    | '/kost/$kostId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalisisRoute: typeof AnalisisRoute
  DataKostRoute: typeof DataKostRoute
  PerbandinganRoute: typeof PerbandinganRoute
  PetaRoute: typeof PetaRoute
  KostKostIdRoute: typeof KostKostIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/peta': {
      id: '/peta'
      path: '/peta'
      fullPath: '/peta'
      preLoaderRoute: typeof PetaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perbandingan': {
      id: '/perbandingan'
      path: '/perbandingan'
      fullPath: '/perbandingan'
      preLoaderRoute: typeof PerbandinganRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/data-kost': {
      id: '/data-kost'
      path: '/data-kost'
      fullPath: '/data-kost'
      preLoaderRoute: typeof DataKostRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analisis': {
      id: '/analisis'
      path: '/analisis'
      fullPath: '/analisis'
      preLoaderRoute: typeof AnalisisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kost/$kostId': {
      id: '/kost/$kostId'
      path: '/kost/$kostId'
      fullPath: '/kost/$kostId'
      preLoaderRoute: typeof KostKostIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalisisRoute: AnalisisRoute,
  DataKostRoute: DataKostRoute,
  PerbandinganRoute: PerbandinganRoute,
  PetaRoute: PetaRoute,
  KostKostIdRoute: KostKostIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
